middle section of my mobile portfolio
brighton0102/Portfolio pull request #2
Opened 2023-05-03 13:27 UTC by brighton0102

In this project I worked on the middle section of my portfolio using HTML and CSS 
I added the following
 Card works section
 About myself section
 And the
 Languages section

2023-05-03 13:48 UTC, IngDavidTM requested changes
## Hi @brighton0102 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 13:48 UTC, IngDavidTM commented on index.html
> +    </article>
- [ ] Great job on creating the works section of your project! However, to improve the semantics of your webpage, it is recommended to use a `section` tag as the container for this section. This will help assistive technologies to better understand the content and organization of your webpage, making it more accessible to users :+1:.

2023-05-03 13:48 UTC, IngDavidTM commented on index.html
> +            </div>
- [ ] Good job listing your skills in the About section :+1:, but for semantics, the technology categories ("Languages", "Frameworks" and "Skills") should be in a `ul`, and each of them in a `li`. Also, the technology in each category(e.g., "JavasScript", "HTML" and "CSS") should be also a list `ul` and each of them a `li`
- [ ] To improve the accessibility and SEO of your website, it is recommended to use HTML elements instead of only images in this section. This will help assistive technologies understand the content of your website and also make it easier for search engines to crawl and index your website :+1:.

2023-05-04 17:04 UTC, V-Blaze approved these changes
Hi @brighton0102  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved-accepted](https://user-images.githubusercontent.com/107632780/229279070-96b4e89d-83fd-4f9f-acc2-649c7cee2957.gif)


## Highlights

- Portfolio looks like the Figma design💯
-  Correct use of HTML semantic tags👍
- Pull request summary is descriptive🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 17:43 UTC, merged